default_gamerules:
  announceAdvancements: "true"
  commandBlockOutput: "true"
  disableElytraMovementCheck: "false"
  disableRaids: "false"
  doDaylightCycle: "true"
  doEntityDrops: "true"
  doFireTick: "true"
  doInsomnia: "true"
  doLimitedCrafting: "false"
  doMobLoot: "true"
  doMobSpawning: "true"
  doTileDrops: "true"
  doWeatherCycle: "true"
  drowningdamage: "true"
  falldamage: "true"
  firedamage: "true"
  keepInventory: "false"
  logAdminCommands: "true"
  maxCommandChainLength: "65536"
  maxEntityCramming: "24"
  mobGriefing: "true"
  naturalRegeneration: "true"
  randomTickSpeed: "3"
  reducedDebugInfo: "false"
  sendCommandFeedback: "true"
  showDeathMessages: "true"
  spawnRadius: "10"
  spectatorsGenerateChunks: "true"
  doImmediateRespawn: "false"